
version: '3.3'

volumes:
  postgres_data:


services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    
  web:
    image: 1523341/yamdb_final:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./static:/app/static
      - ./media:/app/media

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - web
    volumes:
      - ./static:/var/html/static
      - ./media:/var/html/media
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80