version: '3.3' 


services: 
  db: 
    image: postgres:latest 
    restart: always 
    volumes:
      - /var/lib/postgresql/data/
    env_file: 
      - .env
     

  web: 
    image: 1523341/yamdb_final:latest 
    restart: always 
    env_file: 
      - .env 
    depends_on: 
      - db 
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
 
  nginx: 
    image: nginx:alpine 
    restart: always 
    depends_on: 
      - web 
    volumes:

      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - static_value:/var/html/static/

      - media_value:/var/html/media/ 

    ports:
      - "80:80"
      
volumes:

  static_value:
  media_value: